language: node_js

branches:
  only:
    - master

node_js:
  - 0.6
  - 0.7

notifications:
  email:
    - jarno.keskikangas@leonidasoy.fi
  irc:
    channels:
      -"irc.freenode.org#transparency.js"
    use_notice: true
